services: 
  app:
      build: .
      init: true
      ports:
        - "8080:8080"
      depends_on:
        postgres:
            condition: service_healthy
        redis:
            condition: service_started
      environment:
        - DB_DRIVER=postgresql
        - DB_HOST=postgres
        - DB_USER=admin
        - DB_PASSWORD=password
        - DB_NAME=store
        - DB_PORT=5432
        - REDIS_URL=redis:6379
        - JWT_SECRET=americanas-super-secret-jwt-key-2025

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U admin -d store"]
        interval: 10s
        timeout: 5s
        retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
        test: ["CMD-SHELL", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres_data:
  redis_data:
