// @title Americanas Loja API
// @version 1.0
// @description API RESTful para e-commerce
// @host localhost:8080
// @BasePath /api/v1
// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization

package main

import (
	"log"
	"os"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/Code-Aether/americanas-loja-api/docs" // This will be generated by swag init
	"github.com/Code-Aether/americanas-loja-api/internal/config"
	"github.com/Code-Aether/americanas-loja-api/internal/handlers"
	"github.com/Code-Aether/americanas-loja-api/internal/middleware"
	"github.com/Code-Aether/americanas-loja-api/internal/repository"
	"github.com/Code-Aether/americanas-loja-api/internal/services"
	"github.com/Code-Aether/americanas-loja-api/pkg/cache"
	"github.com/Code-Aether/americanas-loja-api/pkg/database"
)

func main() {
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found")
	}

	cfg := config.Load()

	db, err := database.NewConnection(cfg)
	if err != nil {
		log.Fatal("failed to connect to database:", err)
	}

	rdb := cache.NewRedisClient(cfg.RedisURL, "", 0)

	err = database.AutoMigrate(db)
	if err != nil {
		log.Fatal("failed to auto migrate:", err)
	}

	productRepo := repository.NewProductRepository(db)
	userRepo := repository.NewUserRepository(db)
	productService := services.NewProductService(productRepo, rdb)
	authService := services.NewAuthService(userRepo, cfg.JWTSecret)

	productHandler := handlers.NewProductHandler(productService)
	authHandler := handlers.NewAuthHandler(authService)

	err = database.SeedData(db)
	if err != nil {
		log.Fatal("failed to seed data:", err)
	}

	err = database.SeedAdminUser(db)
	if err != nil {
		log.Fatal("failed to create admin user:", err)
	}

	r := gin.Default()

	r.Use(gin.Logger())
	r.Use(gin.Recovery())

	setupRoutes(r, productHandler, authHandler, authService)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting at http://localhost:%s", port)
	log.Fatal(r.Run(":" + port))
}

func setupRoutes(r *gin.Engine, productHandler *handlers.ProductHandler, authHandler *handlers.AuthHandler, authService *services.AuthService) {
	root := r.Group("/")
	{
		root.GET("/health", func(c *gin.Context) {
			c.JSON(200, gin.H{
				"status":    "OK",
				"service":   "americanas-loja-api",
				"version":   "1.0.0",
				"timestamp": time.Now().Format(time.RFC3339),
			})
		})

		root.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	api := r.Group("/api/v1")
	{
		authMiddleware := middleware.NewAuthMiddleware(authService)

		// Authentication routes
		auth := api.Group("/auth")
		{
			auth.POST("/register", authHandler.Register)
			auth.POST("/login", authHandler.Login)
			auth.POST("/refresh", authHandler.RefreshToken)
		}

		// User routes
		user := api.Group("/user")
		user.Use(authMiddleware.RequireAuth())
		{
			user.GET("/profile", authHandler.GetProfile)
			user.POST("/change-password", authHandler.ChangePassword)
			user.POST("/logout", authHandler.Logout)
		}

		// Public Product routes
		public := api.Group("/")
		public.Use(authMiddleware.OptionalAuth())
		{
			public.GET("/products", productHandler.GetProducts)
			public.GET("/products/:id", productHandler.GetProduct)
		}

		// Protected routes (Creation/Update) Products (Login is needed)
		protected := api.Group("/")
		protected.Use(authMiddleware.RequireAuth())
		{
			protected.POST("/products", productHandler.CreateProduct)
			protected.PUT("/products/:id", productHandler.UpdateProduct)
		}

		// Admin only routes
		adminProtected := api.Group("/")
		adminProtected.Use(authMiddleware.RequireAdmin())
		{
			adminProtected.DELETE("/products/:id", productHandler.DeleteProduct)

			adminProtected.GET("/admin", func(c *gin.Context) {
				c.JSON(200, gin.H{
					"message": "Admin list - TODO",
					"admin":   true,
				})
			})

			adminProtected.GET("/admin/users", func(c *gin.Context) {
				c.JSON(200, gin.H{
					"message": "User list - TODO",
					"admin":   true,
				})
			})

			adminProtected.GET("/admin/stats", func(c *gin.Context) {
				c.JSON(200, gin.H{
					"message": "System Stats - TODO",
					"admin":   true,
				})
			})
		}
	}
}
